### ISSUE TITLE
Model hidden and shown events not working

### ISSUE THREAD

**Issue by vishalinfyom** [coreui/coreui#101]
`modal.hidden.bs.modal` and `shown` events not working !

i have following code for modal opening and close :

```
 $(function(){
    $('#changePasswordModal').on('hidden.bs.modal', function () {
        alert();
    });

    $('#changePasswordModal').on('shown.bs.modal', function () {
        alert();
    });
```

and its not working.

**Comment by anthony-clark** [comment]
I believe you have to use the CoreUI event:
```javascript
$('#myModal').on('hidden.coreui.modal', function (e) {
  // do something...
})
```

**Comment by dungmv** [comment]
why rename the bootstrap modal event? instead of rename event from ```hidden.bs.modal``` to ```hidden.coreui.modal``` we can make an alias to use both of them
It makes me confuse and I think many people confuse like me.
