### ISSUE TITLE
[v3] .c-header-nav removes padding on .dropdown-menu

### ISSUE THREAD

**Issue by aidanlister** [coreui/coreui#102]
Looks like this:

<img width="225" alt="Screen Shot 2019-12-18 at 7 37 35 am" src="https://user-images.githubusercontent.com/54896/71043331-491ad780-2169-11ea-9a1d-a7824508717f.png">

Should look like this:

<img width="397" alt="Screen Shot 2019-12-18 at 7 36 15 am" src="https://user-images.githubusercontent.com/54896/71043342-4f10b880-2169-11ea-99fb-e18bd963dee5.png">

**Comment by mrholek** [comment]
Fixed in v3.0.0-rc.3
