### ISSUE TITLE
[v3] .c-app .undefined

### ISSUE THREAD

**Issue by aidanlister** [coreui/coreui#104]
The left sidebar won't collapse when I click the button, I can't see any v3 docs on the sidebar, but I have closely copied the demo.

When I click it I get this:

<img width="460" alt="Screen Shot 2019-12-18 at 7 42 10 am" src="https://user-images.githubusercontent.com/54896/71043570-fbeb3580-2169-11ea-98ef-9241fe83d9e7.png">

**Comment by xidedix** [comment]
Hi @aidanlister 

Please find the docs for v3 here: [https://coreui.io/docs/3.0-beta/](https://coreui.io/docs/3.0-beta/components/sidebar/).

What's in your sidebar class: `<div class="c-sidebar ..." >`?

**Comment by aidanlister** [comment]
```    <div class="c-sidebar c-sidebar-dark c-sidebar-fixed c-sidebar-show c-sidebar-unfoldable">
```

**Comment by aidanlister** [comment]
I was missing `data-target="_parent"` on the minimizer.
