### ISSUE TITLE
[v3] Can't set background-color in sass

### ISSUE THREAD

**Issue by aidanlister** [coreui/coreui#108]
My background colour is coming from reboot.css:
https://github.com/coreui/coreui/blob/v3-next/css/reboot.css#L26

Rather than what I set for $body-bg, which looks like I should be able to customise it per the docs here: https://coreui.io/v1/docs/getting-started/options/

I can't find any equivalent documentation page for V3.

**Comment by mrholek** [comment]
@aidanlister I will fix it next release

**Comment by aidanlister** [comment]
@mrholek thanks that's great

**Comment by mrholek** [comment]
Fixed in v3.0.0-rc.3
