### ISSUE TITLE
Right sidebar (aside) not working properly

### ISSUE THREAD

**Issue by liviumischie** [coreui/coreui#113]
The right sidebar is not working properly when using the free coreui package (version 3.0.0-rc.0). It works fine when using the coreui-pro package (version 3.0.0-rc.1). To be more specific, the margins are not fine for the right sidebar, it still shows a small part of the sidebar, even when the sidebar should be hidden.
I use something like this for the sidebar:
```<div class="c-sidebar c-sidebar-lg c-sidebar-light c-sidebar-right c-sidebar-overlaid" id="aside"></div>```
And for the sidebar toggler:
```<button class="c-header-toggler c-class-toggler mfe-md-3" type="button" data-target="#aside" data-class="c-sidebar-show"></button>```
I did a comparison of "node_modules\@coreui\coreui\scss\_sidebar.scss" and "node_modules\@coreui\coreui-pro\scss\_sidebar.scss" and there are, indeed, some differences.
Can you please fix the sidebar also on the free coreui package?
Thank you!

**Comment by mrholek** [comment]
@liviumischie please send me screenshots

**Comment by liviumischie** [comment]
I have attached a screenshot showing that a part of the right sidebar is still visible, even though it should be completely hidden. If I use the _sidebar.scss from the coreui-pro package instead of the one form the free coreui package, then it works fine.

![coreui_sidebar_issue](https://user-images.githubusercontent.com/18462708/74259655-ebd27b00-4d00-11ea-8cba-27471d3c01f9.png)

**Comment by GitHubHubus** [comment]
Have the same issues. This doesn't work for free version
