### ISSUE TITLE
[V.3.0.0] Showing different Logos in light and dark mode

### ISSUE THREAD

**Issue by ck2000** [coreui/coreui#116]
I am using the following html and CSS to show different logo in the main menu on dark and light mode:

`<div class="c-sidebar-brand">`
     `<img class="c-sidebar-brand-full c-d-light-none" src="/assets/logo_dark.png" height="36">`
     `<img class="c-sidebar-brand-full c-d-dark-none" src="/assets/logo_light.png" height="36">`
     `<img class="c-sidebar-brand-minimized c-d-dark-none" src="/assets/icon_light.svg" width="40" height="40">`
     `<img class="c-sidebar-brand-minimized c-d-light-none" src="/assets/icon_dark.svg" width="40" height="40">`
 `  </div>`

In light mode both images logo_dark.png and logo_light.png are shown. In dark mode everything workes fine.

**Comment by mrholek** [comment]
@ck2000 please change `c-d-light-none` to `c-d-default-none`
