### ISSUE TITLE
Tooltip position bug - flicker from top of screen to final position

### ISSUE THREAD

**Issue by driftingly** [coreui/coreui#118]
The tooltip flickers from the top of the screen to final position:
![tooltip](https://user-images.githubusercontent.com/194221/76236422-e413d280-61e9-11ea-9398-17b3f53f4ac0.gif)

Demo: https://coreui.io/demo/3.0.0/#base/tooltips.html

**OS**: macOS Catalina 10.15.3

The issue appears in:
- Safari Version 13.0.5
- Google Chrome Version 80.0.3987.132 
- Brave Version 1.4.96 Chromium: 80.0.3987.132 

The issue does **not** appear in:
- Firefox 73.0.1 (64-bit)

**Comment by mrholek** [comment]
@driftingly In CoreUI 3.1.0 popper.js will be updated to version 2.x, so this problem should be solved
