### ISSUE TITLE
[v3] Sidebar minimalization not working in Coreui 3.0

### ISSUE THREAD

**Issue by majsterkoo** [coreui/coreui#124]
Hi, after updating from CoreUI 3.0-rc0 to coreui 3.0 sidebar minimalization stop working. When I go to coreui.io/demo/3.1.0 and inject styles with coreui 3.0, it stop working too, so I think it is not my mistake... Class c-sidebar-unfoldable to div with id="sidebar" do nothing. If I try copy css file from sample page with version 3.1.0 to my project, sidebar unfoldable working without problem...

**Comment by TantumLabs** [comment]
I have this same issue the class applies but nothing happens.

**Comment by majsterkoo** [comment]
I Found next bug with sidebar - aside. 3.1.0 style from coreui live example solved problem too, so I think isn't my mistake. When remove z-index from header then aside is on top of header without problem.

![image](https://user-images.githubusercontent.com/3364720/78991978-8c46ef00-7b3a-11ea-9099-c24713957fe2.png)

**Comment by majsterkoo** [comment]
I tested 3.2.0 version and problem still remaining. When change style from 3.1.1 (default page style) to 3.2.0 on coreui demo page, sidebar not working there too. https://coreui.io/demo/3.1.0/#main.html

**Comment by mrholek** [comment]
@majsterkoo `c-sidebar-unfoldable` is not available in the free version, you can use only `.c-sidebar-minimized`.

**Comment by majsterkoo** [comment]
Oh, I didn't notice that. c-sidebar-minimized works. Thank you!
