### ISSUE TITLE
Scrollbar on aside

### ISSUE THREAD

**Issue by kontas** [coreui/coreui#125]
Hi,

using lot of content in the sidebar is impossible, because there is no scrolling bar.

Thanks for your work

**Comment by sharpn** [comment]
I have had the same issue, ended up putting a custom class called `allow-overflow` and adding 
```
ul {
  .c-sidebar-nav {
    &.allow-overflow {
      overflow-y: auto !important;
    }
  }
}
```

to a custom scss file then importing it
