### ISSUE TITLE
[v3] Conflict when a data-toggle toolip is englobing a dropdown

### ISSUE THREAD

**Issue by fakenine** [coreui/coreui#134]
Hello,

I have these errors when I'm trying to encapsulate a dropdown in a span that has a tooltip

![image](https://user-images.githubusercontent.com/5814696/83781213-7c591080-a68e-11ea-89ad-b74fb0e0273d.png)

ie:

```slim
span[data-toggle='tooltip' data-placement='right' title='Some tooltip'
  button.btn.btn-secondary.dropdown-toggle aria-expanded="false" data-toggle="dropdown" type="button"
    i.fa.fa-star
```

CoreUI version: @coreui/coreui-pro@3.1.1
Browser: Firefox 76.0.1 (64 bits)
OS: Ubuntu 18.04 LTS

**Comment by codewise-nicolas** [comment]
We just ran into this same error.
Where you able to fix it somehow? @fakenine
