### ISSUE TITLE
Integrate COREUI Pro on Symfony 4

### ISSUE THREAD

**Issue by JamesStand** [coreui/coreui#138]
Hello.
I recently bought CORE UI Pro, and i would like to use this bundle on my new symfony 4 project.
Im asking myself how to integrate CoreUI Pro on my project now, because i can't find any information on internet.

Do i have to use webpack encore ?

**Comment by ennisthemenace** [comment]
Same issue here

**Comment by JamesStandbridge** [comment]
Ennis, i never find a propre solution.
Im working with copy paste ..

**Comment by ennisthemenace** [comment]
I purchased it and ran npm install @coreui/coreui-pro but yeah I am using npm etc.

**Comment by JamesStandbridge** [comment]
Yep i tried this aswell but i wasn't happy with it, i think its simplier to copy paste to be honest haha

**Comment by ennisthemenace** [comment]
:/

**Comment by mrholek** [comment]
Hi, we're going to release some tutorials on how to integrate CoreUI in existing projects.

**Comment by illuminate3** [comment]
Integrating with Symfony and Stimulus would be nice.

* I have paid for a pro license
