### ISSUE TITLE
tooltip disappears and throws error when element has children

### ISSUE THREAD

**Issue by divinespear** [coreui/coreui#141]
* coreui version: 3.2.2
* Tested with Chrome 84.0.4147.89 and Firefox 78.0.2 on Ubuntu 20.04

Reproduce example:
https://codepen.io/divinespear/pen/vYLbLjJ

example has a button contains svg image.
 1. mouse over child element, tooltip disappears.
 2. mouse out from child element, throw error: `Uncaught TypeError: Cannot read property 'destroy' of null` (chrome) or `Uncaught TypeError: t._popper is null` (firefox) on https://github.com/coreui/coreui/blob/82b54367ff341414e14d26406deca56073e29e67/js/src/tooltip.js#L345

bootstrap works expected.
https://codepen.io/divinespear/pen/bGEzExm

**Comment by divinespear** [comment]
some minutes of research, I found a different between this and bootstrap.

on `_enter()`, this uses `event.target`
https://github.com/coreui/coreui/blob/82b54367ff341414e14d26406deca56073e29e67/js/src/tooltip.js#L614-L623

bootstrap uses `event.delegateTarget`
https://github.com/twbs/bootstrap/blob/c7bc7a31bbc11c3f9af3ad317581cbd13c7bb5f1/js/src/tooltip.js#L589-L598

should I open new PR?

**Comment by wittfabian** [comment]
Same here!

**Comment by mrholek** [comment]
Fixed in v3.3.0
