### ISSUE TITLE
White background for options in dark mode

### ISSUE THREAD

**Issue by eddivalen** [coreui/coreui#144]
Why the background of these options is white? is this intentional?

![image](https://user-images.githubusercontent.com/8193094/90413469-7a430300-e07c-11ea-9f53-ceea1552c4f4.png)

**Comment by wittfabian** [comment]
In the bootstrap version the background is transparent.

**Comment by wittfabian** [comment]
select2-coreui.css: line 233

```
.c-dark-theme .select2-container--coreui .select2-dropdown {
  background-color: rgba(255, 255, 255, 0.1);
  border-color: rgba(255, 255, 255, 0.15);
}
```
should something like ..
```
.c-dark-theme .select2-container--coreui .select2-dropdown {
  background-color: rgba(76, 79, 84, 1);
  border-color: rgba(76, 79, 84, 1);
}
```

I think the select2 theme is in many places not adapted to the dark theme.

**Comment by mrholek** [comment]
Fixed in v3.3.0

**Comment by wittfabian** [comment]
Where can I find the updated verison of select2-coreui.css?
I can only find it in coreui-pro-bootstrap-admin-template-v3.2.0-dist

**Comment by wittfabian** [comment]
@mrholek Where can I find the updated verison of select2-coreui.css?

**Comment by cedricvoinnet** [comment]
@mrholek Any idea of when the updated version of select2-coreui.css be released?

**Comment by mrholek** [comment]
@cedricvoinnet this week we will release v3.4.0

**Comment by michaeltoohig** [comment]
I'm not seeing this update in version 3.4.0. I have the exact issue as the OP.
