### ISSUE TITLE
Collapse sidebar to display icon

### ISSUE THREAD

**Issue by joannelew** [coreui/coreui#147]
The v1 and v2 layout options - Minimized sidebar

- 'Minimized sidebar has 50px width and only icons are visible' had disappeared from coreui pro v3.
 Is it possible to put it back. It was devastating as I upgrade from v2 to v3 and discovered the missing feature.
![image](https://user-images.githubusercontent.com/31501474/90999868-60646b80-e5fa-11ea-82db-7947ff1da97d.png)

**Comment by joannelew** [comment]
Found solution

**Comment by Raoch** [comment]
@joannelew  could you share solution please? I am getting same problem
