### ISSUE TITLE
[v3-pro] Navs-Tabs displayed incorrectly in dark theme

### ISSUE THREAD

**Issue by wittfabian** [coreui/coreui#149]
Navs-Tabs displayed incorrectly in dark theme.

No borders or lines are visible.

https://coreui.io/demo/3.1.0/dark/#base/navs.html

![Bildschirmfoto 2020-09-04 um 16 30 42](https://user-images.githubusercontent.com/8940922/92250803-3a797980-eecc-11ea-8f21-e0a2b191cf9a.png)

![Bildschirmfoto 2020-09-04 um 16 30 35](https://user-images.githubusercontent.com/8940922/92250840-45340e80-eecc-11ea-867e-66169f4ca251.png)

**Comment by mrholek** [comment]
It will be fixed in v3.4.0

**Comment by wittfabian** [comment]
Works, thanks!
