### ISSUE TITLE
[v3-pro] EventHandler for SELECTOR_CLASS_TOGGLER uses stopPropagation

### ISSUE THREAD

**Issue by wittfabian** [coreui/coreui#155]
coreui.bundle.min.js line 2287 - 2311

```
  EventHandler.on(document, EVENT_CLICK_DATA_API$4, SELECTOR_CLASS_TOGGLER, function (event) {
    event.preventDefault();
    event.stopPropagation();
    var toggler = event.target;

    .....
```

In the event handler "stopPropagation" is called. To save the change of the design I use an event handler myself, which is not possible anymore with "stopPropagation".

**Comment by TantumLabs** [comment]
My guess is this causes an issue where my aside won't close. When it use version 3.2.0 it works fine. I have also noticed random event listeners don't work in 3.3.0 as well.

**Comment by mrholek** [comment]
You have to change this:

`<button class="c-sidebar-close c-class-toggler" type="button" data-target="_parent" data-class="c-sidebar-show responsive="true">...</button>`

to this

`<button class="c-sidebar-close c-class-toggler" type="button" data-target="_parent" data-class="c-sidebar-show>...</button>`

**Comment by wittfabian** [comment]
In my case its
```
        <ul class="c-header-nav mfs-auto">
            <li class="c-header-nav-item px-3 c-d-legacy-none">
                <button class="c-class-toggler c-header-nav-btn" type="button" id="theme-toggler" data-target="body"
                        data-class="c-dark-theme" data-toggle="c-tooltip" data-placement="bottom"
                        title="Toggle Light/Dark Mode">
                    <i class="fal fa-moon c-icon c-d-dark-none"></i>
                    <i class="fal fa-sun c-icon c-d-default-none"></i>
                </button>
            </li>
        </ul>
```

**Comment by wittich** [comment]
Just posted the same issue on SO with exmaple...

https://stackoverflow.com/questions/65083133/add-a-click-event-on-a-coreui-element-on-c-class-toggler

**Comment by TantumLabs** [comment]
This isn't just related to .c-class-toggler as with any version above 3.2 ( I have tried 3.3 and 3.4) any element with `.c-subheader-nav-link` blocks additional event listeners as well.

**Comment by MACscr** [comment]
ugh, this is really frustrating as I really want the toggle stated to be stored in the browser for the user and i have no way to hook into the event because of it.

**Comment by wittich** [comment]
Just left detailed answer on SO https://stackoverflow.com/a/68127227/3001970 ...

The trick (_or maybe correct way_) is to hook to existing events... in case of the **sidebar** there is a `classtoggle` event.

Hope that helps someone.
