### ISSUE TITLE
c-d-minimized-none does not set display: none

### ISSUE THREAD

**Issue by oscarlofwenhamn** [coreui/coreui#156]
https://github.com/coreui/coreui/blob/66e747e06cf1fdf51c5eb2b3c66c627f898d9343/scss/_sidebar.scss#L499-L511

This feels unintuitive; setting something to `c-d[isplay]-minimized-none` should do just that, as for certain purposes, such as using `::after`s, it doesn't appear equivalent to set 
```scss
      height: 0;
      padding: 0;
      margin: 0;
      visibility: hidden;
      opacity: 0;
```

Not sure which would be to prefer; a new class like `c-d-minimized-really-none` for setting `display: none`, or adding something like a `c-d-minimized-hidden` to replace the current `c-d-minimized-d`. I'm guessing the former, for backwards compatibility, but I feel the latter would be working more as expected.

### Example
Wide:
![image](https://user-images.githubusercontent.com/44643697/97151497-dbb7da00-176f-11eb-9736-b0e3258a45a4.png)

Minimized with `c-d-minimized-none`:
![image](https://user-images.githubusercontent.com/44643697/97151460-d195db80-176f-11eb-8a43-994e072f5cde.png)

Minimized with `c-d-minimized-really-none`:
![image](https://user-images.githubusercontent.com/44643697/97151770-436e2500-1770-11eb-8514-23b1c5419c09.png)

**Comment by mrholek** [comment]
@oscarlofwenhamn You're right, the name of this class is not good, we will change this in v4. We don't use `display: none` because it breaks CSS transition.

**Comment by oscarlofwenhamn** [comment]
Sounds good! Let me know if you'd like this issue closed, leaving it open for now to serve as a checkbox.
