### ISSUE TITLE
sidebar link doesn't activate when url has  a hash.

### ISSUE THREAD

**Issue by 0xcdcdcdcd** [coreui/coreui#158]
I think there is a mistake in the regular expression listed in the _setActiveLink function in file sidebar.js.

`-        var urlHasParams = /\\?.*=/;`
`-        var urlHasQueryString = /\\?./;`
`+       var urlHasParams = /\?.*=/;`
`+       var urlHasQueryString = /\?./;`

**Comment by mrholek** [comment]
@0xcdcdcdcd can you paste me an example url?

**Comment by 0xcdcdcdcd** [comment]
"dashboard" menu doesn't activate.

[sample.zip](https://github.com/coreui/coreui/files/5560875/sample.zip)

**Comment by mrholek** [comment]
If you want to use CoreUI with Vue.js you should try the dedicated version https://github.com/coreui/coreui-vue

**Comment by 0xcdcdcdcd** [comment]
I attached a simple hash sample.

[sample2.zip](https://github.com/coreui/coreui/files/5570539/sample2.zip)
