### ISSUE TITLE
Buttons active state

### ISSUE THREAD

**Issue by jfrosorio** [coreui/coreui#163]
For some reason, you removed the active state from the buttons mixins. Because of this, applying the `.active` class to a button won't force its active state.

Checkout Bootstrap's 4.5.3 buttons mixin:
```
@mixin button-variant($background, $border, $hover-background: darken($background, 7.5%), $hover-border: darken($border, 10%), $active-background: darken($background, 10%), $active-border: darken($border, 12.5%)) {
  (...)

  &:not(:disabled):not(.disabled):active,
  ->-> &:not(:disabled):not(.disabled).active, <-<- THIS LINE IS MISSING IN COREUI
  .show > &.dropdown-toggle {
    (...)
  }
}
```

**Comment by srodriki** [comment]
Experiencing the same here I'm afraid. Any ideas how to fix it?

**Comment by jfrosorio** [comment]
Hi @srodriki

I patched it by overriding the primary button styles like so:
```
.btn-primary
{
    &:not(:disabled):not(.disabled).active{
        color: color-yiq(darken($primary, 10%));
        background-color: darken($primary, 10%);
        @if $enable-gradients {
            background-image: none; // Remove the gradient for the pressed/active state
        }
        border-color: darken($primary, 12.5%);

        &:focus {
            @if $enable-shadows and $btn-active-box-shadow != none {
                @include box-shadow($btn-active-box-shadow, 0 0 0 $btn-focus-width rgba(mix(color-yiq($primary), $primary, 15%), .5));
            } @else {
                // Avoid using mixin so we can pass custom focus shadow properly
                box-shadow: 0 0 0 $btn-focus-width rgba(mix(color-yiq($primary), $primary, 15%), .5);
            }
        }
    }
}
```

That's enough for me because I don't really need it to work for the other buttons. If you want to fix all the buttons, you can repeat this code for each style (which is not ideal) or you can try to write a mixin to fix them all.

It is a pity that the owners do not care about this bug. It's a quick fix, so I really don't understand why it's taking so long for them to do something about it...

**Comment by jfrosorio** [comment]
Lol, more than 1 year later, no response to a very simple problem. Nice support!
