### ISSUE TITLE
Where is slack coreui slack channel?

### ISSUE THREAD

**Issue by ToddHoff** [coreui/coreui#18]
Slack is mentioned as a place to ask questions, yet it's not referenced anywhere. There's a bootstrap slack, but that doesn't seem like it would be the proper place.

**Comment by leobarcellos** [comment]
+1

**Comment by col-panic** [comment]
It's really hard to get in touch with them, even if you have a paid pro license - support is not even answering mails ...

**Comment by mrholek** [comment]
Hi @ToddHoff at this moment we can't provide support via Slack channel. We're going to hire more people to provide better support and open Slack and Gitter channel. 

@col-panic I'm sorry if I didn't answer your email, probably I missed something out.

**Comment by leobarcellos** [comment]
Maybe it would be nice to create it @mrholek, we could exchange some information as clients until you get a support team ready to help us :)

**Comment by col-panic** [comment]
@mrholek thx for your answer - then please have a look at request 895! thanks

**Comment by ToddHoff** [comment]
> Hi @ToddHoff at this moment we can't provide support via Slack channel. We're going to hire more people to provide better support and open Slack and Gitter channel.
> 
> @col-panic I'm sorry if I didn't answer your email, probably I missed something out.

Not a single question from a single channel was even replied to. I gave up on this software a long time ago.

**Comment by col-panic** [comment]
@ToddHoff can't confirm that - I got a reply from them, after posting the problem in here.
