### ISSUE TITLE
CSS parsing and mixin error 

### ISSUE THREAD

**Issue by Govind9673** [coreui/coreui#213]
I have updated core/coreui-pro library from 2.1.16 to 3.4.2.

Getting below issues while compiling

Error: C:/Users/GRajpurohit/Desktop/workspace/vp-angular-update/technicalportal/src/scss/vendors/toastr/toastr.scss 
C:/Users/GRajpurohit/Desktop/workspace/vp-angular-update/technicalportal/src/scss/vendors/toastr/toastr.scss:1:1: Unknown word
You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser

Error: ./src/scss/style.scss Module build failed (from ./node_modules/mini-css-extract- 
plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined mixin.
     ╷
19 │ @include _assert-ascending($grid-breakpoints, "$grid-breakpoints");
   │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules\@coreui\coreui-pro\scss\variables\_grid.scss 19:1  @import
  node_modules\@coreui\coreui-pro\scss\_variables.scss 19:9       @import
  src\scss\_variables.scss 2:9                                    @import
  src\scss\style.scss 2:9                                         root stylesheet

**Comment by mirazzaq** [comment]
@Govind9673 did you find a resolution for this?
