### ISSUE TITLE
Sidebar minimizer not re-instantiating perfectScrollbar

### ISSUE THREAD

**Issue by codewise-nicolas** [coreui/coreui#218]
Browser: All

Summary: The sidebar minimizer is not re-instantiating the perfectScrollbar

Demo: https://coreui.io/demo/free/3.4.0/buttons/buttons.html
Minimize the sidebar, then re-expand, the perfectScrollbar goes away and you get the browser default scrollbar

Long Description:
Looked into the code and it appears the class-toggler is removing the class and then firing the event, the sidebar component is looking for the c-sidebar-minimized class in order to reset() the sidebar and thus re-init the perfect scrollbar, however at that point the class has been removed by the class-toggler and thus the code never runs.
This may be an old example/demo but looking thru the docs and the code I could not find anything newer/working.

**Comment by fklee** [comment]
Same issue for me ! on version 3.4.0

**Comment by codewise-nicolas** [comment]
Well as it seems no one cares about this legitimate issue on coreui team we ended up just patching it for now.
It only applies to the full js bundle, so if you use the minified version you will need to re-minify the full version and if you include/require coreui via your app.js good luck.

Using NPM's patch-package we made the following patch:

```
diff --git a/node_modules/@coreui/coreui/dist/js/coreui.bundle.js b/node_modules/@coreui/coreui/dist/js/coreui.bundle.js
index c5e9cfc..ed850b0 100644
--- a/node_modules/@coreui/coreui/dist/js/coreui.bundle.js
+++ b/node_modules/@coreui/coreui/dist/js/coreui.bundle.js
@@ -8474,12 +8474,12 @@
     };
 
     _proto.reset = function reset() {
-      if (this._element.classList.contains(CLASS_NAME_SIDEBAR_MINIMIZED)) {
+      //if (this._element.classList.contains(CLASS_NAME_SIDEBAR_MINIMIZED)) {   //Fix the fancy scrollbar not getting re-inited on minimize-expand due to some race condtion on the classes
         this._element.classList.remove(CLASS_NAME_SIDEBAR_MINIMIZED);
 
         this._minimize = false;
         EventHandler.one(this._element, TRANSITION_END, this._psInit());
-      }
+      //}
 
       if (this._element.classList.contains(CLASS_NAME_SIDEBAR_UNFOLDABLE)) {
         this._element.classList.remove(CLASS_NAME_SIDEBAR_UNFOLDABLE);
```

**Comment by fklee** [comment]
Thanks for the correction, As you said "good luck" is for me Thanks :-)
