### ISSUE TITLE
COREUI PRO

### ISSUE THREAD

**Issue by FerdieAquino** [coreui/coreui#23]
Greeting !!!

I Purchase a COREUI Pro License where can i get the latest release of this product and where to email incase we have an product inquiry or need support.

Thank you very much.

:) Regards,
Ferdie Aquino

**Comment by mrholek** [comment]
Hi, please give me your email. I will send you link latest version.

**Comment by FerdieAquino** [comment]
Ferdie_Aquino@yahoo.com

Thank you very much
