### ISSUE TITLE
TypeError: Cannot set property 'Constructor' of undefined

### ISSUE THREAD

**Issue by noideawoman** [coreui/coreui#235]
Im use coreui pkg like this at my site.

```
<script src="https://unpkg.com/@popperjs/core@2"></script>
<script src="https://unpkg.com/@coreui/coreui/dist/js/coreui.min.js"></script>
```

my site used to work. However, when I checked it today, I got this error.

```
Uncaught TypeError: Cannot set property 'Constructor' of undefined
```

I want you to check it as soon as possible.

**Comment by mrholek** [comment]
Yesterday we released version 4.0, you have to update your link to use the previous version.

`<script src="https://unpkg.com/@coreui/coreui@3.4.0/dist/js/coreui.min.js"></script>`
