### ISSUE TITLE
Pro-Demo seems partially broken, Pro-NPM not up2date, Pro-SCSS not working as it should

### ISSUE THREAD

**Issue by cewlbird** [coreui/coreui#287]
Hi dear coreui-team,

we have a pro license and tried to update from 3.4 to 4.0.4.
Also we are using NPM for loading the files.

The whole layout seems broken as the .wrapper styles are not loading like it is in your demo.
It seems like the LTR-Mixin is not working which should load the .wrapper style as this  should create the left padding for the wrapper/sidebar.

Also the bottom button for toggling the sidebar is not working as well in your 4.0 demo.

Additionally there is no 4.0.5 pro version available on packagist (only available for coreui free).
We also don't understand if we should include bootstrap before loading coreui 4 and also which version for coreui 4 should be used (Bootstrap 5?)?

Is core ui 4 a working version or is it maybe still an alpha or beta version?

Best Regards

**Comment by mrholek** [comment]
The versions of CoreUI PRO and CoreUI can be different.

There are a lot of changes in CoreUI 4, please check this - https://coreui.io/docs/4.0/migration/

Please check src/scss folder in CoreUI 4 PRO template, and check if you have all these files in your project.

**Comment by nessimabadi** [comment]
Hi, 
Currently using the free version of CoreUI.
Migrating from 3 to 4.

I had the same problem with the wrapper and the sidebar minimizer not working.
There's no mention on the migration docs about the wrapper.

Is there a change that should be made to the layout for it to work?

Thanks for the help
