### ISSUE TITLE
nav-underline classes are missing from React code in v4.0.5

### ISSUE THREAD

**Issue by colincalnan** [coreui/coreui#289]
The React documentation for Nav shows an option for an underline variant https://coreui.io/react/docs/4.0/components/navs-tabs/#underline

`<CNav variant="underline">`

It seems that the CSS `.nav-underline` for this has been removed  in version 4.0.5 as I can't find it in this repository.

I did a `yarn add @coreui/coreui` and my `node_modules/@coreui/dist/css/coureui.css` file is showing

```
/*!
 * CoreUI - HTML, CSS, and JavaScript UI Components Library
 * @version v4.0.5
 * @link https://coreui.io/
 * Copyright (c) 2021 creativeLabs Łukasz Holeczek
 * License MIT  (https://coreui.io/license/)
 */
 ```
In your documentation site, the classes are available in the styles that are being loaded...

https://coreui.io/react/docs/4.0/styles.9f8abf46fe75185855f2.css

and that file is showing v4.0.4??

Has the underline variant been deprecated in 4.0.5?

**Comment by mrholek** [comment]
`nav-underline` is available only in CoreUI PRO

**Comment by colincalnan** [comment]
Thanks @mrholek , perhaps the documentation could add a "PRO" badge to that specific section?

https://coreui.io/react/docs/4.0/components/navs-tabs/#underline

**Comment by mrholek** [comment]
You're right, I will add this to our docs
