### ISSUE TITLE
npm install fails with npm dependency error - cannot find unist-util-is-4.0.5

### ISSUE THREAD

**Issue by colincalnan** [coreui/coreui#290]
Steps to reproduce

1. Clone repo
2. Checkout `main` branch - there is no `master` branch as per Contrib. docs. https://github.com/coreui/coreui/blob/main/.github/CONTRIBUTING.md
3. Run `npm install`
4. Receive error

```
$ npm install
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/unist-util-is/-/unist-util-is-4.0.5.tgz - Not found
npm ERR! 404 
npm ERR! 404  'unist-util-is@https://registry.npmjs.org/unist-util-is/-/unist-util-is-4.0.5.tgz' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by colincalnan** [comment]
I think I have found the issue in `package.json`

Search for `"karma-jasmine": "^4.0.5",`
It seems this version is incorrect. The most recent version of this is `4.0.1` - https://www.npmjs.com/package/karma-jasmine

I changed the version in the `package.json` file 

`"karma-jasmine": "^4.0.1",`
Then I ran these commands in the project directory
```
$ rm -rf node_modules
$ npm cache clean --force
$ npm install
```
and it worked!

**Comment by mrholek** [comment]
@colincalnan thank you for your help, I will release a new version with your fix at the beginning of next month.

**Comment by colincalnan** [comment]
@mrholek, looking good, I just pulled ans `npm install` works well on `v4.1.0`. Thank you.
