### ISSUE TITLE
Access to Core-ui Pro Repo

### ISSUE THREAD

**Issue by jedjones-uk** [coreui/coreui#30]
I have purchased the Core-ui membership version, and have a license key. How do I get access to the private repo on github? 

I tried emailing support@coreui.io but the email was rejected because the user was unknown.

At the moment, I am pretty disappointed at the process of getting the pro version as they seem to be unmaintained, and very unclear beyond the payment part.

**Comment by mrholek** [comment]
Sorry for the inconvenience. I will fix it asap

**Comment by Avkash** [comment]
I have exact same problem. I have bought the PRO license and now I have the key. What should I do with the key? There is no documentation telling how to apply the license key. Please suggest.

**Comment by mrholek** [comment]
@Avkash do you have active membership plan?

**Comment by mrholek** [comment]
@Avkash  In your repository, you have two files:

- 1.0.8 - it's old version for clients who use version 1.x
- coreui-pro-all-frameworks-2018-12-04 - the latest version of CoreUI

You don't have to use license at this moment. We generate it to identify our clients.

**Comment by Avkash** [comment]
Thanks @mrholek, merry Christmas!!!

I am using the latest coreui-pro-react-admin-template-2.1.2 now. I wanted to use webpack for the development mode, however it does not have webdev.config.. the older 1.0.8 does have webdev.config.x

The directory structure is very different so it is not easy to port. Do you have webdev.config for the latest 2.12 react project?

**Comment by xidedix** [comment]
hi @Avkash 
CoreUI v2 for React is bootstrapped with [Create React App](https://github.com/facebook/create-react-app) and webpack under the hood. Please refer to CRA docs about configuration options. You can also eject webpack scripts out of CRA. This is a one-way operation though.

**Comment by Bleedingmascara** [comment]
Hi @mrholek
I just purchased the 99$ Core UI Pro (all versions) but i haven't received an email so far. Where can i find the access for those repositories please?

**Comment by rlewis86** [comment]
Hello @mrholek,
My company purchased the All Frameworks Core UI Pro on 2/11.  We received the license key but no links to download files.  I put in a support ticket same day we ordered and have still not heard anything.  Please advise.

**Comment by mrholek** [comment]
@rlewis86 please send me your license number to lukasz [at] coreui . io

**Comment by rlewis86** [comment]
For anyone else having this issue:  Deal directly with support@gumroad.com.

I tried emailing @mrholek directly as well as support@coreui.io twice.  No answer from them after 10 days of waiting.  I would give them the benefit of the doubt that their email was blocked by our corporate filter, but when I put in for support, the auto-generated email from their domain came through instantly.

Needless to say, I am thoroughly disappointed that the only way we got support is when we asked for a refund.  Gives me no hope for future support down the road.

**Comment by mrholek** [comment]
@rlewis86 I sent you the message that you don't have an active membership plan, so we can't give you access to our private repositories.

**Comment by rlewis86** [comment]
@mrholek I was not looking for access to the Github repository.  Our issue was that we never received the files to begin with.  My company purchased access to the "All Frameworks" pro package and only received a license key.   

I actually fought to use your templates as they look really professional and well thought out.  After persuading my company to use it, we had to wait 10 days to get download links.  Just makes me look bad.  That's what was disappointing.   The first email I've received for any "core ui" support was from you about 10 minutes ago.

**Comment by dariodepaolis** [comment]
@mrholek I bought the standard license, how can I access to future updates?

**Comment by mrholek** [comment]
@dariodepaolis You will be notified via email when a new version will be ready to download.

**Comment by mrholek** [comment]
@rlewis86 I just checked all messages we sent to you. After payment ( Feb 11) gumroad sent to you following message. 
<img width="578" alt="zrzut ekranu 2019-02-22 21 45 02" src="https://user-images.githubusercontent.com/3524167/53270299-a8e05780-36eb-11e9-9228-e85944b3db59.png">
, so you should have access to all files, just click green button "View product".

**Comment by CharliePyper** [comment]
I havent received a welcome email, and also looking to be able to refresh the view from within the view. Looking like I need the unmiminfied coreui.js please can you help

**Comment by CharliePyper** [comment]
I sorted this with the following:

$(".click_view").on("click", function () {
    var viewurl=$(this).attr('href');
    $.ajax({
        type: 'GET',
        url: viewurl,
        success: function (e) {
            $("#ui-view").html(e);
        }
    });
    return false;
});


in your view you need to add the "click_view" class to your link <a href="url to be displayed in view" class="click_view">Click on me</a> This will capture the click event, Get the value in href and using ajax load the requested response in the ui-view div.

**Comment by GizzmoAsus** [comment]
Evening @mrholek,
Can you grant me access to the pro repository please?

I can send you my license code if required 👍

**Comment by pincusgl** [comment]
I also bought the Core Pro and have thew licsense.. I download form the email but I want to copy from repo

Thanks Pincus

**Comment by mrholek** [comment]
@pincusgl do you have active membership plan?

**Comment by pincusgl** [comment]
I paid 69 and Have the licensee.. And it says that I will have access to
private repository. DO you need my license number?

Pincus Glauber
UniPro International
390 Nye Ave - Irvington NJ 07111
Office: 973-577-1300 Ext 1002
Direct: 347-623-2439

**Comment by mrholek** [comment]
@pincusgl I just checked and you bought "CoreUI Pro Vue.js Standard License". Access to private GitHub repositories is available only for clients who subscribed to the Membership Plan. Please check our pricing table - https://coreui.io/pro/vue/#buy

We can't offer this feature in standard licenses because we have to pay GitHub $9 monthly per additional user.

**Comment by ttarzan1** [comment]
Hi,
In the case of not finding better way to contact you about the updates/versions, I am writing here. Tried to get you over support email, but no luck.

We would love to purchase Big Bundle, but we have some doubts about future versions. If we buy that bundle or any other product in the matter of fact, do we also have access to the future versions ( in this case version 3 ) for all the products ?

Thank you!

**Comment by mrholek** [comment]
Hi @ttarzan1, 

We're going to change some license terms when version 3 will be ready, but if you buy a licence before release you will get lifetime access to future releases.

Regards
Lukasz

**Comment by ttarzan1** [comment]
Well sorry, I have few more question. As I understood correctly, buying Big Bundle will give me access to version 3 and later versions, but I need to buy it, before license change. Right?

The question is, I don't see access to version 3 if we purchase $69 CoreUI PRO React.js, SOLO LICENSE only for $99 SOLO LICENSE. Do we have access to future versions, like version X ?

On page [https://coreui.io/bundles/big-bundle/](https://coreui.io/bundles/big-bundle/), it says Big Bundle but the price is $99. Typo ? 

So generally, what is the difference between Big Bundle $199 and All frameworks + Sketch $99 ?

Thank you.

**Comment by mrholek** [comment]
Yes, Big Bundle will give you access to version 3.

Vue.js, React.js & Angular version 3 is not ready, we're going to release them later this month. If you buy solo license you will also get free update to version 3.

In Big Bundle ($199) we have CoreUI PRO All frameworks + all templates

**Comment by rezahuaroc** [comment]
coreui otra basura mucha gente estafada,...... quieres comprar plataforma desactualizada, deseas soporte te responden mas una mes,... tiras de basuras

**Comment by the-invisible-man** [comment]
Hey @mrholek, I got CoreUI (React) as a Christmas present yesterday from my brother. How do I get access to the private repo? I received the email with the links to download CoreUI but my brother used a different email account than the one I use for my Github so I'm not sure if that's got something to do with. Thanks!
