### ISSUE TITLE
Multi-Select supports remote data

### ISSUE THREAD

**Issue by cedricvoinnet** [coreui/coreui#307]
Multi-Select is said to be the replacement of Select2 on Coreui 4 but while migrating from 3.4 to 4.1, I ended up with a problem on Select2 with remote data.

I tried to tweak my Multi-Select instance to update it on the user search but everytime the input is completely cleared, the menu closed and every selection made is removed.

Multi-Select seems not to be ready to replace Select2 on this type of tasks.

I think that an update to take into account remote data might be necessary to really replace Select2.

**Comment by mrholek** [comment]
@cedricvoinnet thank you for your feedback, I will check how can we add this to our MultiSelect component.
