### ISSUE TITLE
Multi-Select overlaps main content div in demo

### ISSUE THREAD

**Issue by wittfabian** [coreui/coreui#308]
The multi-select component shifts the end of the screen and thus creates a white border (very problematic with long lists). A scrollbar like in select2 would be a good solution.

- Operating system and version: MacOS 11.6.1
- Browser and version: all Browsers

<img width="1792" alt="Bildschirmfoto 2021-12-24 um 14 19 43" src="https://user-images.githubusercontent.com/8940922/147356380-dc748ed7-bd9e-43ae-84f2-c6918ba7958c.png">

**Comment by wittfabian** [comment]
Any updates?

**Comment by mrholek** [comment]
You use `date-coreui-options-max-height`
