### ISSUE TITLE
Tab-content class seems to miss some definition

### ISSUE THREAD

**Issue by cedricvoinnet** [coreui/coreui#316]
On the theme's examples, there is no padding, no background and the examples for the horizontal tabs that are supposed to have the tabs on the right and left do not work.

I think something is missing for this part of Coreui.

![image](https://user-images.githubusercontent.com/10754693/148747300-68d88838-3da2-47ea-88bb-b02b570aa4cc.png)
![image](https://user-images.githubusercontent.com/10754693/148747576-dc6d8372-6472-46dd-9246-8a9edb3e7bc9.png)

- Operating system and version: Ubuntu 20.04
- Browser and version: all Browsers

**Comment by Slokilla** [comment]
Up please, it's broken even in your demo : 
![image](https://user-images.githubusercontent.com/51393687/168855785-e00cb469-64f6-4b7f-ab56-ae85018a326e.png)
