### ISSUE TITLE
Scss variable to control nav-group-items padding

### ISSUE THREAD

**Issue by meriturva** [coreui/coreui#328]
To make possible something like:

![image](https://user-images.githubusercontent.com/5664195/150331345-a342d7ae-e184-4ac0-b580-f3c3dfd037f6.png)

i have modified CSS as:

```
.nav-group-items {
  padding-left: 20px !important;
}
```

I guess it is better to have padding-x padding-y of nav-group-items scss variables.

What do you think?

**Comment by mrholek** [comment]
@meriturva I will add this in next release

**Comment by mrholek** [comment]
Added in v4.1.1
