### ISSUE TITLE
Angular validation classes -> remove ng-valid/invalid style

### ISSUE THREAD

**Issue by meriturva** [coreui/coreui#404]
Please could you revert the commit: https://github.com/coreui/coreui/commit/90f99f31ad5e44423dd6d5acb16b35c3414f52d0

this is a big problem in many cases, adding style directly to `ng-valid` and `ng-invalid` classes produces a few problems:

1) usually visual validation/invalidation visual effects are shown only after users touch or submit forms. Now with that commit is always visible
2) many times developers just add a specific class to add validation styles...for example (see is-invalid class)

```
<input class="form-control" type="text" name="subject" [(ngModel)]="subject"
              #subjectModel="ngModel" placeholder="Inserisci il titolo..." autocomplete="subject" required
              [ngClass]="{ 'is-invalid': f.submitted && subjectModel.invalid }">
            <div *ngIf="f.submitted && subjectModel.invalid" class="invalid-feedback">
              <ng-container *ngIf="subjectModel.errors?.required">Titolo richiesto</ng-container>
            </div>
```
now it is impossible to control it.

The hack I use right now to make things work as before:

```
.form-control.ng-valid {
  border-color: #b1b7c1;
  background-image: none;
}

.form-control.ng-invalid {
  border-color: #b1b7c1;
  background-image: none;
}

.ng-submitted {
  .form-control.ng-invalid {
    border-color: $form-feedback-invalid-color;
    background-image: $form-feedback-icon-invalid;
  }
}
```

**Comment by xidedix** [comment]
fixed in `v4.1.5`
