### ISSUE TITLE
Offcanvas not working

### ISSUE THREAD

**Issue by michelebenolli** [coreui/coreui#405]
The `.offcanvas-start` and `offcanvas-end` classes do not produce a working offcanvas component. 
The sidebar does not show in page above the backdrop.
The behavior is reproducible from the documentation at https://coreui.io/docs/components/offcanvas/ by clicking the "Toggle right offcanvas button".
The issue seems not browser-related.

**Comment by JerryBels** [comment]
I can't reproduce your issue, it works well for me. Maybe you have a weird browser quirk, try it in private mode or in another browser?
