### ISSUE TITLE
Colors of demo

### ISSUE THREAD

**Issue by cedricvoinnet** [coreui/coreui#449]
After updating to Coreui 4.3.2 Pro, it seems like the colors defined are not the same as the ones on the demo :

Demo : ![secondary of demo](https://user-images.githubusercontent.com/10754693/182558978-2ff26f63-f2dd-4aca-a6b8-ba0659aa0bd5.png)

Mine : ![my secondary](https://user-images.githubusercontent.com/10754693/182559651-9eee090b-55f7-48a2-8d6a-3bfe05840b66.png)

I can't find the same colors of [4.3](https://coreui.io/demos/bootstrap/4.3/default-v3/buttons/buttons.html). All my colors are the one of [4.2](https://coreui.io/demos/bootstrap/4.2/default/buttons/buttons.html)

**Comment by Slokilla** [comment]
The all layout looks different. As exemple, i don't have the same shadows. I feel like I have the old SASS file.
