### ISSUE TITLE
Compile Issue with Core UI Dark Style in 2.0.20 (but not 2.0.19)

### ISSUE THREAD

**Issue by adrianliechti** [coreui/coreui#49]
(please navigate me to to right place if that is the wrong repo for core ui dark issues)

Error while Compiling:

ERROR in ./node_modules/@coreui/coreui-pro/dist/css/themes/coreui-dark.min.css (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/@coreui/coreui-pro/dist/css/themes/coreui-dark.min.css)
Module Error (from ./node_modules/postcss-loader/src/index.js):
(Emitted value instead of an instance of Error) CssSyntaxError: xxxx/..\..\..\scss\_sidebar.scss:454:41: Can't resolve '%27data:,%27' in 'xxxxx/node_modules/@coreui/coreui-pro/dist/css/themes'

  452 |       .sidebar {
  453 |         .nav {
> 454 |           list-style-image: url("data:,");
      |                                         ^
  455 |           .divider {
  456 |             height: 0;

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
OSX

- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
N/A

- Reduced test cases and potential fixes using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

- Create Angular 7 Project
- npm install @coreui/coreui-pro@2.0.20
- In angular.js, add "node_modules/@coreui/coreui-pro/dist/css/themes/coreui-dark.min.css" to projects/architect/build/styles

Workaround: Downgrade to 2.0.19

**Comment by cluen** [comment]
Same here with free edition: 2.1.0
```
    "@coreui/angular": "^2.0.0",
    "@coreui/coreui": "^2.1.0",
    "@coreui/icons": "^0.3.0",
```

Error:
```
ERROR in ./node_modules/@coreui/coreui/dist/css/coreui.min.css (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/@coreui/coreui/dist/css/coreui.min.css)
(Emitted value instead of an instance of Error) CssSyntaxError: C:\git\scss\_sidebar.scss:455:41: Can't resolve '%27data:,%27' in 'C:\git\xxxxx\xxxxx\node_modules\@coreui\coreui\dist\css'

  453 |       .sidebar {
  454 |         .nav {
> 455 |           list-style-image: url("data:,");
      |                                         ^
  456 |           .divider {
  457 |             height: 0;
```

**Comment by xidedix** [comment]
Looks like this workaround for rtl ie11 issue breaks somehow scss compilation.

We’re working on it.

**Comment by xidedix** [comment]
```css
list-style-image: url("data:,");
```
after minification turns into:
```css
list-style-image: url("'data:,'");
```

**Comment by xidedix** [comment]
Hi @adrianliechti @cluen 
Please update `@coreui/coreui` to `^2.1.1` and let us know if this works for you

`coreui-pro` is scheduled for an update later this week

**Comment by cluen** [comment]
@xidedix: works!

**Comment by xidedix** [comment]
@adrianliechti @cluen thanks for the heads up on this one.
`coreui-pro` has also been updated
