### ISSUE TITLE
Multi-select not selecting "selected: true" items (Vue)

### ISSUE THREAD

**Issue by BandHun** [coreui/coreui#541]
Vue Multi Select not selecting selected items.

It is an issue in the docs too.
https://coreui.io/vue/docs/forms/multi-select.html

It's good in Angular, React and JS.

OS: Ubuntu and IOS
Browser: Firefox, Chrome, Safari

**Comment by gbrrrl-no** [comment]
I haven't been able to replicate the problem on iOS. Which section of the document are you having problem with?
