### ISSUE TITLE
coreui is not defined

### ISSUE THREAD

**Issue by nasirkhan** [coreui/coreui#607]
I am using the CoreUI free version for one of my projects. It is a Laravel 10 project and I am using Vite to build the project. 

After migrating the project from Webpack to Vite I am getting an error on the sidebar toggle button. When I click on the button it throws an error 

```
coreui is not defined
```

for the code below

```
<button class="header-toggler px-md-0 me-md-3" type="button" onclick="coreui.Sidebar.getInstance(document.querySelector('#sidebar')).toggle()">       
```

Can you please let me know the reason of this issue and way to fix it? 

Project URL: https://github.com/nasirkhan/laravel-starter/blob/update/resources/views/backend/includes/header.blade.php

**Comment by aidanlister** [comment]
Hey @nasirkhan, you might want to post this as a discussion over here (https://github.com/coreui/coreui/discussions) and see if the community can jump in and show you how to set up CoreUI with Vite, as this is not a bug in CoreUI itself.

**Comment by mrholek** [comment]
@nasirkhan please check if the following file `coreui.bundle.js` is available in this view
