### ISSUE TITLE
Vulnerabilities with jQuery version used

### ISSUE THREAD

**Issue by rajbdilip** [coreui/coreui#73]
`npm` reported one of the dependencies of core-ui, *jQuery 1.9.1* has the following two vulnerabilities.

1. Prototype Pollution (Severity: Moderate)
2. Cross Site Scripting (Severity: High)

Upgrading jQuery version to `1.12.2` resolves _XSS_ but _Prototype Pollution_ still remains.

I have the following queries. (Kindly note that I intent to use the plugin in a corporate environment. So, the vulnerabilities are concerns).

1. Will core-ui break if I upgrade jQuery to 1.12.1 since the default dependency added by core-ui is 1.9.1? I'm assuming there are no breaking changes since it's a minor version upgrade.
2. NPM suggests jQuery 3.4.x for remediation of both the vulnerabilities. Since, 3.x would have 
 breaking API changes (I'm assuming again here. Please correct if I'm wrong), are there any plans for the upgrade anytime soon?

**Comment by jameswilson** [comment]
The [getting started](https://coreui.io/docs/getting-started/introduction/) section in the documentation suggests that coreui is compatible with at least 3.3.1   Maybe a PR that just updates the dependency in package.json would be accepted by the maintainer?
