### ISSUE TITLE
Getting to CoreUI v3.0.0

### ISSUE THREAD

**Issue by mrholek** [coreui/coreui#74]
Hi,

I'm pleased to announce that after several months of development we are ready to share with you first version of CoreUI 3.x. The general plan for CoreUI 3.x development starts with a few alpha releases. Expect another alpha releases this and next month. 

Here you can find the latest version of CoreUI:

- [CoreUI 3 Library](https://github.com/coreui/coreui/tree/v3-next)
- [CoreUI 3 Free Admin Template](https://github.com/coreui/coreui-free-bootstrap-admin-template/tree/v3-next)
- [CoreUI 3 Pro Demo](https://coreui.io/demo/3.0/#main.html)

We are looking forward to your ideas and comments.

**Comment by fancydev18** [comment]
Hi, thanks for the update!

Any estimate for what needs to be done to release v3, and when that will happen?

**Comment by mrholek** [comment]
@fancydev18 we're going to release CoreUI v3.0.0-beta this month

**Comment by fancydev18** [comment]
Any updates, please? Will the Vue version also get a beta release?

**Comment by madalinignisca** [comment]
I saw some mentions about Laravel on the blog. Any additional hints about what do you plan for it?

**Comment by JanBN** [comment]
Is there a react version of core ui 3 ?

**Comment by xidedix** [comment]
At the moment there are following flavors of CoreUI 3 (Beta):
- CoreUI 3 Static & XHR
- CoreUI 3 Vue.js
- CoreUI 3 Laravel

Later this year we are going to release:
- CoreUI 3 Laravel for Vue.js
- CoreUI 3 React.js
- CoreUI 3 Angular

**Comment by ccamacho** [comment]
@mrholek hi, any estimate for the beta 3 for react? Thanks and merry x-mas!

**Comment by mrholek** [comment]
@ccamacho we're going to release React version this month

**Comment by Wo0nder** [comment]
Have news about 3 for Angular?

**Comment by xidedix** [comment]
> Have news about 3 for Angular?

@Wo0nder We're on it.

**Comment by Wo0nder** [comment]
> > Have news about 3 for Angular?
> 
> @Wo0nder We're on it.

Sorry, but I did not find where to download CoreUI 3, for the angular. I bought a pro version, but it has templates from Core UI 3 and separately Angular Core UI 2.

**Comment by ccamacho** [comment]
@Wo0nder I think as the React version it's not yet released, I hope it will be released soon :)

**Comment by ccamacho** [comment]
@mrholek Any update for the react version?

**Comment by vkhemlan** [comment]
Hi! We're also looking forward to the release of Core UI 3 for React. Any news would be greatly appreciated.

Also, thanks for the amazing work on this project.
