### ISSUE TITLE
Remember state of sidemenu 

### ISSUE THREAD

**Issue by pbzrpa** [coreui/coreui#75]
Hi, 

Thank you for the great template. One feature would be nice is if one could specify a cookie name to remember the state of the side menu. Currently you minimize the menu and the moment it goes to any other page it maximizes again.  Some users would prefer that the menu remain in it's current state.

Thanks

Using CoreUI v2.1.3

**Comment by mrholek** [comment]
Hi,

I will try to add this feature in v3.

Regards
Lukasz

**Comment by pbzrpa** [comment]
Hi, great thanks.

**Comment by tabacitu** [comment]
@pbzrpa until v3, this worked for me in the current version:

```html
    <script type="text/javascript">
      /* Recover sidebar state */
      if (Boolean(sessionStorage.getItem('sidebar-collapsed'))) {
        var body = document.getElementsByTagName('body')[0];
        body.className = body.className.replace('sidebar-lg-show', '');
      }

      /* Store sidebar state */
      var navbarToggler = document.getElementsByClassName("navbar-toggler");
      for (var i = 0; i < navbarToggler.length; i++) {
        navbarToggler[i].addEventListener('click', function(event) {
          event.preventDefault();
          if (Boolean(sessionStorage.getItem('sidebar-collapsed'))) {
            sessionStorage.setItem('sidebar-collapsed', '');
          } else {
            sessionStorage.setItem('sidebar-collapsed', '1');
          }
        });
      }
    </script>
```
Hope it helps.

**Comment by pbzrpa** [comment]
Thank you, I can definitely work with this :-) It unfortunately does not work with the minimized menu (the one that only show icons) maybe you can include that in v3. I appreciate your help.

**Comment by Lucky-Loek** [comment]
I've fixed it like this in my CoreUI integration for Laravel: https://github.com/HZ-HBO-ICT/Laravel-CoreUI/blob/master/resources/assets/js/toggle_sidebar.js

```js
/**
 * Show the sidebar
 */
let showSidebar = function() {
    let body = document.getElementsByTagName('body')[0];
    body.classList.remove('brand-minimized');
    body.classList.remove('sidebar-minimized');
};

/**
 * Returns true if sidebar should be shown, false if it shouldn't.
 * @returns {boolean}
 */
let sidebarShouldBeShown = function() {
    return window.localStorage.getItem('remember_sidebar') === 'true';
};

if (sidebarShouldBeShown()) {
    showSidebar();
}

```

**Comment by fancydev18** [comment]
The code above doesn't work with v3.

There should be a setTimeout() to wait for DOM.

This is better:
```
    let sidebarCollapseButtons = document.getElementsByClassName('c-sidebar-minimizer')
    if (sidebarCollapseButtons.length > 0) {
        //might not be visible
        sidebarCollapseButtons[0].addEventListener('click', toggleSidebarItem)
    }
```

'remember_sidebar' doesn't make sense. Please use 'sidebar_state' with values 'minimized' or 'full'

`showSidebar` should be `minimizeSidebar`, as sidebar is full by default.

**Comment by aidanlister** [comment]
@fancydev18 or @Lucky-Loek do you have any updated code for v3?

**Comment by ijaureguialzo** [comment]
Hello, using this code the sidebar remembers it's state on v3, but the opening animation is triggered every time the page is loaded and I can't disable it.

I would appreciate any suggestion:

```javascript
$(document).ready(function ($) {
    $('.c-header-toggler').bind('click', function (e) {
        e.preventDefault();
        if (Boolean(localStorage.getItem('sidebar-toggle-expanded'))) {
            localStorage.setItem('sidebar-toggle-expanded', '');
        } else {
            localStorage.setItem('sidebar-toggle-expanded', '1');
        }
    });
});

$('#sidebar').ready(function (e) {
    if (localStorage.getItem("sidebar-toggle-expanded") !== null) {
        if (localStorage.getItem("sidebar-toggle-expanded") === '1') {
            $("#sidebar").addClass('c-sidebar-lg-show');
        }
    }
});
```

**Comment by jynxy** [comment]
@ijaureguialzo ive tried this on v3.1.0 and doesnt work for me ? have you tried on this version ?

**Comment by ijaureguialzo** [comment]
No, sorry. I ended using a Javascript call to my backend and storing the status in the session so it's available on page reload and I can set the correct class.

**Comment by jynxy** [comment]
ok thanks. +1 for this feature.

**Comment by jynxy** [comment]
i believe i have this working for 3.1.0 if someone wants to test and improve then please do so. im no expert in JS 

`<script id="rendered-js">
var $toggleButton = $('#c-class-toggler');
var $pushSelector = $('#sidebar');
var sidebarIsOpen;
var openSidebarOnLoad = true;
var debug = false;

function toggleSidebar()
{
	sidebarIsOpen = !sidebarIsOpen;
	
	if ($pushSelector.hasClass('c-sidebar-unfoldable'))
	{
		$pushSelector.addClass('c-sidebar-unfoldable');
		if(debug)
		{
			console.log('The \'c-sidebar-unfoldable\' class has been removed.');
		}
	}
	if (sidebarIsOpen)
	{
		$pushSelector.removeClass('c-sidebar-unfoldable');
		localStorage.setItem('sidebar', 'opened');
		if(debug)
		{
			console.log('The \'opened\' storage item has been set.');
		}
	}
	else
	{
		$pushSelector.addClass('c-sidebar-unfoldable');
		localStorage.setItem('sidebar', 'closed');
		if(debug)
		{
			console.log('The \'closed\' storage item has been set.');
		}
	}
}

if (localStorage.getItem('sidebar') === null)
{
	sidebarIsOpen = openSidebarOnLoad;
	if(debug)
	{
		console.log('The default state is ' + openSidebarOnLoad);
	}
}
else
{
	if (localStorage.getItem('sidebar') === 'opened')
	{
		sidebarIsOpen = true;
		if(debug)
		{
			console.log('The \'opened\' storage item is set; the sidebar should be open.');
		}
	}
	else
	{
		sidebarIsOpen = false;
		if(debug)
		{
			console.log('The \'closed\' storage item is set; the sidebar should be closed.');
		}
	}
}

if (sidebarIsOpen)
{
	$pushSelector.removeClass('c-sidebar-unfoldable');
	if(debug)
	{
		console.log('The \'c-sidebar-unfoldable\' class has been removed; the sidebar should be open.');
	}
}
if (!sidebarIsOpen)
{
	$pushSelector.addClass('c-sidebar-unfoldable');
	if(debug)
	{
		console.log('The \'c-sidebar-unfoldable\' class has been added; the sidebar should be closed.');
	}
}

$toggleButton.on('click', toggleSidebar);
</script>`

you can clear the storage with this button

`<button onclick="localStorage.clear(); alert('localStorage has been cleared');">Clear localStorage</button>`

hope it works well for you. :)

**Comment by jynxy** [comment]
forgot to add you need to add id="c-class-toggler"  to the button for it to work.

**Comment by airliajsmith** [comment]
+1 for this feature.
