### ISSUE TITLE
CDN link is incorrect for version 5.0.1

### ISSUE THREAD

**Issue by kylewschultz** [coreui/coreui#761]
The file https://github.com/coreui/coreui/blob/main/docs/content/getting-started/introduction.md contains a {cdn.css} param. 

This param renders https://coreui.io/bootstrap/docs/getting-started/introduction/
The URL for the rendered CSS CDN URL is:
`<link href="https://cdn.jsdelivr.net/npm/@coreui/coreui@5.1.0/dist/css/coreui.min.css" rel="stylesheet" integrity="sha384-hazw3X5QZ2q1iOnw6S3SywpZC1h7tIuXVRXTBTvI5a/mNy+BHeenuvDTNgFv12f5" crossorigin="anonymous">
`
I believe this should be **coreui@5.0.1** as the 5.1.0 link does not work and the 5.0.1 link does. 

This is the same for the JS file(s) as well.

**Comment by happyman** [comment]
or "https://cdn.jsdelivr.net/gh/coreui/coreui@5.0.1/dist/css/themes/bootstrap/bootstrap.min.css"
and "https://cdn.jsdelivr.net/gh/coreui/coreui@5.0.1/dist/js/bootstrap.bundle.min.js"

**Comment by kylewschultz** [comment]
@happyman not sure what your comment relates to.  I know those are the links that should be used however the documentation on the website is incorrect. 
![image](https://github.com/coreui/coreui/assets/48213370/e82408e7-0ef8-4c33-9b14-ed0f3c18b784)

**Comment by mrholek** [comment]
@kylewschultz I'm working on it. I appreciate your help!

**Comment by kylewschultz** [comment]
@mrholek - No problem! I was going to submit a PR but wasn't sure where the params came from. Great product. How can I contribute?
