### ISSUE TITLE
Make customizable nav-item margin-top: 1px;

### ISSUE THREAD

**Issue by meriturva** [coreui/coreui#767]
See here:

https://github.com/coreui/coreui/blob/main/scss/sidebar/_sidebar-nav.scss#L74

is it possible to have a variable to control that?
I mean: `margin-top: 1px;`

Thanks.

**Comment by meriturva** [comment]
Still relevant!

**Comment by meriturva** [comment]
Still relevant!

**Comment by mrholek** [comment]
Added new CSS variable ```--#{$prefix}sidebar-nav-gap: #{$sidebar-nav-gap};```

**Comment by meriturva** [comment]
Thanks @mrholek !
