### ISSUE TITLE
When the sidebar is hidden and "unfoldable" is set to true, the padding-left is not removed.

### ISSUE THREAD

**Issue by dannycandra** [coreui/coreui#828]
### Description
When the sidebar is hidden, a left padding remains in the content area, but this only occurs when "unfoldable" is set to true. This issue is present in versions 5.1.1 and 5.1.2. I tested versions 5.0.0 through 5.1.0, where it worked as expected.

I think !important is the problem here.

This css
```
.sidebar-narrow-unfoldable:not(.sidebar-end) ~ * {
  --cui-sidebar-occupy-start: 4rem !important;
}
```

overwrote this one

```
@media (min-width: 992px) {
  .sidebar.hide:not(.sidebar-end) ~ * {
    --cui-sidebar-occupy-start: 0;
  }
}
```

### Steps to Reproduce
1. Clone repot `git clone https://github.com/coreui/coreui-free-react-admin-template`
2. Install dependencies with `npm install`
3. Check if coreui version 5.1.1 & 5.1.2 in package.json
4. Click on the sidebar-toggler on the sidebar-footer to set sidebar unfoldable to true
5. Click on the hamburger-menu to hide the sidebar

### Expected behavior
The behavior of hiding the sidebar should remain consistent, regardless of whether "unfoldable" is set to true or false.
![grafik](https://github.com/user-attachments/assets/b8421f4e-487d-4672-91ca-e8d959622195)

### Actual behavior
Visible left padding
![Screenshot 2024-09-20 153100](https://github.com/user-attachments/assets/2ff87a5f-80e8-47c6-85dd-ace8650896f5)

### Environment
Please complete the following information:
- OS: Windows
- Browser: Firefox, Chrone

**Comment by mrholek** [comment]
fixed
