### ISSUE TITLE
data-bs not working in bootstrap version

### ISSUE THREAD

**Issue by tecdnb** [coreui/coreui#834]
Hi,

In the bootstrap version of coreui, the data-bs attribute does not work.
I'm using Composer package, but I also checked the source on github and it has data-coreui instead of data-bs.

**Comment by vladrusu** [comment]
I second that.
Looking in the code, there are many lines where coreui mistakenly appears (instead of bs):
```
    setDataAttribute(element, key, value) {
      element.setAttribute(`data-coreui-${normalizeDataKey(key)}`, value);
    },
    removeDataAttribute(element, key) {
      element.removeAttribute(`data-coreui-${normalizeDataKey(key)}`);
    },
```

**Comment by mrholek** [comment]
fixed
