### ISSUE TITLE
[3.0] Need to be more clear on what screen I am

### ISSUE THREAD

**Issue by fancydev18** [coreui/coreui#84]
Hello and thanks for the CoreUI framework!

We've seen users confused about the screen they're in, as it's not clear:
![Screenshot](https://user-images.githubusercontent.com/45625044/65950618-148b5f80-e447-11e9-92c3-313e5740b1c5.png)

Other dashboards, eg Shopify, clearly show the current screen title: 
![Screenshot](https://user-images.githubusercontent.com/45625044/65950624-181ee680-e447-11e9-9d3b-642ae3ceae42.png)

Please consider these improvements:
1. add current page title as heading, similar to Shopify
2. change colors of the right navbar, to clearly show current page

PS: we've seen having current screen on the breadcrumb doesn't help. Breadcrumb is mostly ignored, left navigation bar is used.

Thanks!

**Comment by vincent-guo** [comment]
You can change colors for yourself.
".c-sidebar .c-sidebar-nav-link.c-active" for 3.0 or ".sidebar .nav-link.active" for 2.0.

**Comment by fancydev18** [comment]
Right Vincent, these are suggestions to improve the default template. If these aren't considered useful for other users, feel free to close this issue.
Thanks

**Comment by mrholek** [comment]
@fancydev18 we will check if we can improve this

**Comment by luposky** [comment]
In your docs is much more clean: 

![image](https://user-images.githubusercontent.com/1070180/69431775-affacb80-0d38-11ea-97aa-3877b32457f8.png)
