### ISSUE TITLE
[3.0] left sidebar is worse than 2.0

### ISSUE THREAD

**Issue by fancydev18** [coreui/coreui#88]
Looking at left sidebar in 2.0 vs 3.0, I observed two issues:

1. default width is larger. Extra space is taking valuable real estate to be used for an actual app functionality, not just navigation.

2. collapsed sidebar (bottom '<' icon) UX is worse. In 3.0, the whole sidebar shows on mouse hover, which is disrupting for users.
The collapsed sidebar is for power users who already learned the left navigation menu. For them, seeing only icons with tooltips is enough. The way 2.0 works is very good: show full sub-menu items only for the currently hovered icon, while still keeping sidebar collapsed.

Please consider addressing these issues. They are a blocker for us from using 3.0.

Thanks

**Comment by mrholek** [comment]
Hi @fancydev18 

1. In the beta version, we're going to add CSS classes which allows you to make the sidebar smaller, ex `.c-sidebar-sm`

2. The old minimized sidebar is also available in 3.0, it has the same behavior as in version 2.0.  On our demo page, you can check the new version variant of the sidebar. We called it `.c-sidebar-unfoldable`

**Comment by fancydev18** [comment]
Thanks @mrholek , 

1. Looking forward to try it in the vue beta!

2. Would you please confirm the ```.c-sidebar-unfoldable``` represents the folding '<' icon at the bottom?
![Screenshot from 2019-10-15 08-56-58](https://user-images.githubusercontent.com/45625044/66803947-d81d3080-ef29-11e9-9e61-d5c1187475ae.png)

If so, yes, that folds the sidebar. But the minimized sidebar behaviour is different than 2.0.

Btw, because the minimized sidebar is fully shown now on mouse hover, there seem to be no effect when clicking the minize '<' icon. One has to click and then leave the area with the mouse to notice any effect. Users will clearly think that doesn't do anything when clicked.

**Comment by fancydev18** [comment]
Thanks for fixing these in beta1!
