### ISSUE TITLE
[https://coreui.io] has no link or button to login for paid members

### ISSUE THREAD

**Issue by l2aelba** [coreui/coreui#89]
Hello, I'm a paid member here.

When I come back to https://coreui.io, I can't see any section/button/link to **User area** for download the example templates/invoices/licenses (or I cant find)

**So question is:**
How can I go to **User area** on https://coreui.io?

thanks.

**Comment by l2aelba** [comment]
Project is not active anymore?

**Comment by mrholek** [comment]
Hi @l2aelba, at this moment we're using https://gumroad.com as our payment provider. We're going to build the portal for our clients next year.
