### ISSUE TITLE
[v3] Can't remove CSubheader

### ISSUE THREAD

**Issue by fancydev18** [coreui/coreui#95]
Removing breadcrumb in v2 worked fine, but removing this in v3 from TheHeader
```
        <CSubheader class="px-3">
            <CBreadcrumbRouter class="border-0" />
        </CSubheader>
```
results still in a large header instead of simply having the 2nd row removed:

![Screenshot from 2019-11-04 10-57-14](https://user-images.githubusercontent.com/45625044/68108991-205cbc80-fef2-11e9-88b0-6cd8c68ddca1.png)

**Comment by fancydev18** [comment]
The proper way to remove is removing this line:

>        with-subheader

**Comment by fancydev18** [comment]
Actually, that still leaves a top padding:
```
.c-main {
    -webkit-box-flex: 1;
    -ms-flex: 1;
    flex: 1;
    min-width: 0;
    padding-top: 2rem;
}
```

I guess the fix is having the padding-top applied only when subheader class is present?

**Comment by woothu** [comment]
We cannot reproduce this bug. Can you deliver a screenshot and code?

**Comment by fancydev18** [comment]
I see what you mean. On the default template it still looks good.

We want to have 0 padding when there's no header, so we can set our own content.
But, we can simply overwrite that.

More details on the original request:
https://coreui.io/demo/3.0-alpha.1/#main.html

remove `c-header-with-subheader` from header
```
<header class="c-header c-header-light c-header-fixed">
```

and this div
```
<div class="c-subheader">
```

Without that class, this padding should be 0
```
.c-main {
    padding-top: 2rem;
```

but the default template looks better with it. Closing.
