### ISSUE TITLE
[v3] CHeaderBrand doesn't work with a different image size

### ISSUE THREAD

**Issue by fancydev18** [coreui/coreui#97]
```CSidebarBrand``` works great with customizing height and leaving out width. The resulted img is also centered vertical and horizontal. Perfect!

```CHeaderBrand``` doesn't work the same, though. 

1. Specifying ```height=36``` has no effect.
Cause: ```.c-header-brand``` forces ```height: 56px``` -- that should be removed?

2. The resulted img is NOT centered vertical, but it should be.

3. This also breaks the image, should be removed:
```
@media (min-width: 768px)
.c-header-brand {
    width: 256px;
}
```

**Comment by woothu** [comment]
When I tested it had effect if also changed width.
