### ISSUE TITLE
[v3] please don't overwrite btn display

### ISSUE THREAD

**Issue by fancydev18** [coreui/coreui#98]
v3 sets btn CSS to ```display: inline-flex;```

https://github.com/coreui/coreui/blob/a44067f71780ca6a4094c73ea7fec968c78815f0/scss/_buttons.scss#L8

This breaks centered text in for custom width buttons.

Please leave it to bootstrap default, which is inline-block and works fine.

**Comment by mrholek** [comment]
@fancydev18 will be changed in next release
