### ISSUE TITLE
[v3] Please allow removal of icons

### ISSUE THREAD

**Issue by fancydev18** [coreui/coreui#99]
After upgrading to v3, vendors bundle size increased with 500kb. (vue build)

One of the causes is icons. In previous version, those could be removed with

```
npm uninstall flag-icon-css simple-line-icons coreui-icons --save
```

In V3:
```
npm uninstall @coreui/icons --save
```

doesn't work because of this dependency in main.js
```
import { CIconPlugin } from '@coreui/icons/vue'
Vue.use(CIconPlugin)
```

Please move the CIconPlugin to vue build (https://github.com/coreui/coreui-free-vue-admin-template or coreui-vue?)
instead of bundling it with the icons. We don't any of the bundled the icons. One should be able to use font-awesome instead (which works fine with CIconPlugin)

Thanks

**Comment by fancydev18** [comment]
@woothu Not sure if this is specific to vue version only?

**Comment by woothu** [comment]
Hi! 

1. It is moved to @coreui/icons now, it is not part of this (issue) library.
2. Dependency in main.js would be removable if you remove CIcon components from whole template.
3. The size of the bundle is probably coming from importing icons in assets/icons/icons.js which will be used in 3.0 version to import needed icon (which by the way is the solution for your 500kB bundle even if you will still use our icons).

**Comment by fancydev18** [comment]
Hi and thanks for the details!

> 1. The CIconPlugin is moved to @coreui/icons now because it is strongly related to icons library
Right, but also it doesn't depend on those icons. It works fine with font-awesome.
Seems like coreui-vue would be a better fit.

> 2. Dependency in main.js would be removable if you remove CIcon components from whole template.
I did already, but app won't run then, gives error on CSidebarNavLink which still depends on CIcon.
I'd like to use this component, as I'm not sure if there's a an alternative.

> 3. The size of the bundle is probably coming from importing icons in assets/icons/icons.js 
That was already removed.

vue-cli-service build --report shows 
coreui-vue.common.js at 620k (without details, can't tell what's included there) and 
coreui-icons-vue.common.js at 49kb (so not that large, but still better without it)

**Comment by woothu** [comment]
Ad.1 No it is not compatible with FA by default, although you can convert FA icons to be compatible (valuable thing though, to consider compatibility with FA)
Ad.2 That's true, This is a bug to fix. 
Ad.3 That's insane what webpack did with 2kB of code o.O I will investigate that.

**Comment by fancydev18** [comment]
Thanks, @woothu !

> 2 That's true, This is a bug to fix.

To be fixed part of this report, right? No need to file another issue.
Removing CSidebarNavLink component dependency of CIcon would solve this issue, we can then remove the icons from package.json and all good.

We're ok (and prefer) using ```<i class="far fa-address-book"></i>```, no need for a component to render this.

**Comment by woothu** [comment]
Yes, no need for another issue :) 

CSS Font icons are working but using them exceeds bundle size (compared to single js imports), 
btw. SVG icons have many other advantages i.e. lossless scalability

**Comment by woothu** [comment]
In the latest version CIconPlugin coreui-icons and coreui-icons-vue became seperate libraries.

Moreover, CIcon plugin no longer exists, due to the new way of registering icons.

CIcon component is now bundled in coreui-vue library.

**Comment by fancydev18** [comment]
You rock! Thanks :)
